AttendenceSystem/Controllers/AttendencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendenceSystem;

namespace AttendenceSystem.Controllers
{
    public class AttendencesController : Controller
    {
        private SMEntities db = new SMEntities();

        // GET: Attendences
        public ActionResult Index()
        {
            ViewBag.Departments = new SelectList(db.Departments, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: Attendences/GetStudents
        [HttpPost]
        public ActionResult GetStudents(int departmentId)
        {
            var students = db.Students.Where(s => s.departmentId == departmentId).ToList();
            return PartialView("_AttendanceTable", students);
        }



        [HttpPost]
        public ActionResult CheckAttendance(int departmentId, DateTime attendanceDate)
        {
            var exists = db.Attendences.Any(a => a.attendenceDate == attendanceDate && a.Student.departmentId == departmentId);
            return Json(new { exists });
        }


        [HttpPost]
        public ActionResult GetAttendance(int departmentId, DateTime attendanceDate)
        {
            var attendances = db.Attendences.Where(a => a.attendenceDate == attendanceDate && a.Student.departmentId == departmentId).ToList();
            return PartialView("_AttendanceEditTable", attendances);
        }

        [HttpPost]
        public ActionResult SaveAttendance(List<Attendence> attendances)
        {
            try
            {
                foreach (var attendance in attendances)
                {
                    // Check if there is existing attendance data for the specified date
                    var existingAttendance = db.Attendences.FirstOrDefault(a => a.attendenceDate == attendance.attendenceDate && a.studentId == attendance.studentId);

                    if (existingAttendance != null)
                    {
                        // Update existing attendance record
                        existingAttendance.isPresent = attendance.isPresent;
                        db.Entry(existingAttendance).State = EntityState.Modified;
                    }
                    else
                    {
                        // Insert new attendance record
                        db.Attendences.Add(attendance);
                    }
                }
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                // Handle exceptions
                ModelState.AddModelError("", "An error occurred while saving attendance data." + ex);
                // Return to the view with the current model state
                return View("YourView", attendances);
            }
            return RedirectToAction("Index");
        }






        // Other existing actions...

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendenceSystem/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendenceSystem;

namespace AttendenceSystem.Controllers
{
    [Authorize]
    public class DepartmentsController : Controller
    {
        private SMEntities db = new SMEntities();

        // GET: Departments
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "departmentId,departmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "departmentId,departmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendenceSystem/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendenceSystem;

namespace AttendenceSystem.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private SMEntities db = new SMEntities();

        // GET: Students
        public ActionResult Index()
        {
            //var students = db.Students.Include(s => s.Department);
            var students = db.Students.Include("Department").OrderBy(s => s.studentId).ToList();
            return View(db.Students.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.departmentId = new SelectList(db.Departments, "departmentId", "departmentName");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "studentId,studentFirstName,studentLastName,departmentId,studentEmail")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.departmentId = new SelectList(db.Departments, "departmentId", "departmentName", student.departmentId);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.departmentId = new SelectList(db.Departments, "departmentId", "departmentName", student.departmentId);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "studentId,studentFirstName,studentLastName,departmentId,studentEmail")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.departmentId = new SelectList(db.Departments, "departmentId", "departmentName", student.departmentId);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendenceSystem/Views/Shared/Dept_Counts.cshtml
@model IEnumerable<AttendenceSystem.Department>

@{
    ViewBag.Title = "Department";
    int counter = Model.Count();
}
    <div class="card">
        <p class="card-header">Total Departments</p>

        <div class="card-body">
            @counter
        </div>
    </div>

AttendenceSystem/Views/Shared/LoginCard.cshtml
@using AttendenceSystem.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}

<main aria-labelledby="title">
    <div class="login-container login-form">
        <div class="col-md-8">
            <section id="loginForm">
                @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <h4 class="modal-title">Please Login</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 col-form-label" })
                        <div class="row-cols-md-auto">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 col-form-label" })
                        <div class="row-cols-md-auto">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row-cols-sm-1">
                        <div class="offset-md-2 col-md-10">
                            <div class="checkbox">
                                @Html.CheckBoxFor(m => m.RememberMe)
                                @Html.LabelFor(m => m.RememberMe)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="offset-md-2 col-md-10">
                            <input type="submit" value="Log in" class="btn btn-outline-dark" />
                        </div>
                    </div>
                    <p class="btn-outline-light">
                        @Html.ActionLink("Register as a new user", "Register")
                    </p>
                    @* Enable this once you have account confirmation enabled for password reset functionality
                        <p>
                            @Html.ActionLink("Forgot your password?", "ForgotPassword")
                        </p>*@
                }
            </section>
        </div>
    </div>
</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AttendenceSystem/Views/Shared/SideMenu.cshtml
<link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />


<div class="wrapper">
    <nav class="sidebar">
        <div class=" col-12" style="color:black;">
            <div class="leftItem btn-outline-primary" style="letter-spacing:3px;color:black;">
                @Html.ActionLink(" Home", "Index", "Home", new { area = "" }, new { @class = "nav-link fas fa-home" })
            </div>

            <div class="leftItem btn-outline-primary" style="letter-spacing: 3px; color: black;">
                @Html.ActionLink(" Departments", "Index", "Departments", new { area = "" }, new { @class = "nav-link fas fa-building" })
            </div>

            <div class="leftItem btn-outline-primary" style="letter-spacing: 3px; color: black;">
                @Html.ActionLink(" Students", "Index", "Students", new { area = "" }, new { @class = "nav-link fas fa-user-graduate" })
            </div>

            <div class="leftItem btn-outline-primary" style="letter-spacing: 3px; color: black;">
                @Html.ActionLink(" Attendance", "Index", "Attendences", new { area = "" }, new { @class = "nav-link fas fa-calendar-check" })
            </div>

            <div class="leftItem btn-outline-primary" style="letter-spacing: 3px; color: black;">
                @Html.ActionLink(" Profile", "Index", "Manage", new { area = "" }, new { @class = "nav-link fas fa-user" })
            </div>
        </div>
    </nav>
</div>

AttendenceSystem/Views/Shared/Students_Counts.cshtml
@model IEnumerable<AttendenceSystem.Student>

@{
    int counter = Model.Count();
}

<h2>Students Information @counter</h2>

AttendenceSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SMSystem</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
        }

        .navbar {
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
        }

        footer {
            background-color: darkslategray;
            color: white;
            text-align: center;
            padding: 10px 0;
            width: 100%;
            height: 50px;
            position: sticky;
            bottom: 0;
        }

        .content {
            flex: 1;
            margin-top: 0px;
        }


        .leftMenu {
            display: flex;
            flex-direction: column;
            background-color: #EEF7FF;
            box-shadow: 4px 0 4px rgba(0, 0, 0, 0.5);
            width: fit-content;
            margin-top: 2px;
            margin-left: 2px;
            margin-right: 1px;
            position: absolute;
        }

        .bg-top {
            background-color: darkslategray;
        }

        .textBlack {
            color: black;
        }

        .wrapper {
            display: flex;
            width: 100%;
            flex: 0;
        }

        .sidebar {
            width: 260px;
            height: 100%;
            position: sticky;
            margin-top: 0px;
            top: 0;
            bottom: 0;
            background: #EEF7FF;
            color: black;
            padding-top: 1rem;
            padding-bottom: 1rem;
            overflow-y: auto;
            transform: translateX(0);
            transition: transform 0.3s ease-in-out;
            box-shadow: 1px 0 2px rgba(0, 0, 0, 0.5);
            font-family: Arial;
            font-size: 16px;
        }

        .custom-font {
            font-family: Arial;
            font-size: 16px;
        }

        .active-link {
            background-color: #007bff;
            color: white !important;
            font-weight: bold;
        }

        .nav-link {
            display: inline-block;
            padding: 10px;
        }

        .setting-link.active {
            background-color: #007bff;
            color: white !important;
            font-weight: bold;
        }


    </style>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-top">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-end">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <main class="content">
        <div class="d-sm-inline-flex d-md-flex">
            <div>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.Partial("SideMenu")
                }
            </div>

            <div class="container body-content">
                @RenderBody()
            </div>
        </div>
    </main>

    <footer>
        <p>&copy; @DateTime.Now.Year - Md Washim Akram. All rights reserved.</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        // Get the current page path (not full URL)
        const currentPath = window.location.pathname;

        // Get all menu items
        const menuItems = document.querySelectorAll('.sidebar .leftItem .nav-link');

        // Loop through menu items and highlight the active link
        menuItems.forEach(item => {
            if (item.getAttribute('href') === currentPath) {
                item.classList.add('active-link');
            }
        });

    </script>
</body>

</html>